"""create users table

Revision ID: 78ce87caeb4d
Revises: 
Create Date: 2025-11-09 18:01:37.284242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ce87caeb4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email (уникальный)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон (опционально, уникальный)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хэшированный пароль (Argon2)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='URL аватара'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтверждён ли email'),
    sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='Заблокирован ли'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата регистрации'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Последний вход'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone', name='uq_users_phone'),
    comment='Таблица зарегистрированных пользователей'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
