from enum import Enum
from typing import Protocol


class LogLevel(Enum):
    DEBUG = "debug"
    INFO = "info"
    NOTICE = "notice"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
    ALERT = "alert"
    EMERGENCY = "emergency"


class LoggerProtocol(Protocol):
    def emergency(self, message: str, context: dict | None = None) -> None: ...
    def alert(self, message: str, context: dict | None = None) -> None: ...
    def critical(self, message: str, context: dict | None = None) -> None: ...
    def error(self, message: str, context: dict | None = None) -> None: ...
    def warning(self, message: str, context: dict | None = None) -> None: ...
    def notice(self, message: str, context: dict | None = None) -> None: ...
    def info(self, message: str, context: dict | None = None) -> None: ...
    def debug(self, message: str, context: dict | None = None) -> None: ...
    def log(
        self, level: LogLevel, message: str, context: dict | None = None
    ) -> None: ...
